server:
  port: 8890
spring:
  application:
    name: gible-trade
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: dev
        serviceName: gible-trade
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        register: true
