server:
  port: 8890
spring:
  application:
    name: gible-trade
  cloud:
    consul:
      host: localhost
      port: 8500
feign:
  circuitbreaker:
    enabled: true

management:
  server:
    port: 4453
