spring:
  application:
    name: gible-user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true

server:
  port: 8899

management:
  server:
    port: 4452

feign:
  circuitbreaker:
    enabled: true

resilience4j.ratelimiter:
  instances:
    user:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100