spring:
  application:
    name: gible-user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: dev
        serviceName: gible-user
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        register: true

server:
  port: 8899
