spring:
  application:
    name: gible-user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true

server:
  port: 8899

management:
  server:
    port: 4452
